kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: projected-shared-resource-node-privileged-binding
subjects:
  - kind: ServiceAccount
    name: csi-driver-projected-resource-plugin
    namespace: openshift-cluster-csi-drivers
roleRef:
  kind: ClusterRole
  name: projected-shared-resource-privileged-role
  apiGroup: rbac.authorization.k8s.io