kind: Service
apiVersion: v1
metadata:
  name: shared-resource-csi-driver-node-metrics
  namespace: openshift-cluster-csi-drivers
  labels:
    app: shared-resource-csi-driver-node
spec:
  selector:
    app: shared-resource-csi-driver-node
  ports:
    - name: metrics
      port: 6000
